<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
    <PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\AssettoServer\AssettoServer.Shared\AssettoServer.Shared.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="..\..\external\AssettoServer\AssettoServer\AssettoServer.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <Target Name="PackagePlugin" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <PropertyGroup>
      <PluginPackageDirectory>$(MSBuildProjectDirectory)\..\..\artifacts\PoliceChasePlugin</PluginPackageDirectory>
    </PropertyGroup>
    <MakeDir Directories="$(PluginPackageDirectory)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginPackageDirectory)" />
  </Target>
</Project>
